### ISSUE TITLE
No way to join waitlist without being mod (My Fix)

### ISSUE THREAD

**Issue by ghost** [atomjack/plugbotapi#36]
```
PlugBotAPI.prototype.joinwaitlist = function() {
  if (this.pageReady === true) {
          $( "#dj-button" ).trigger( "click" );
  }
};
PlugBotAPI.prototype.joinwaitlist();
```

**Comment by ImGrumpy** [comment]
Interesting idea... Do you have an equivalent for leaving the waitlist?  It's the same button but it has a confirmation... not sure how to handle that.

**Comment by ghost** [comment]
Sorry for the delay

PlugBotAPI.prototype.joinwaitlist = function() {
  if (this.pageReady === true) {
          $( "#dj-button" ).trigger( "click" );
          $(".submit").trigger( "click" );
  }
};
PlugBotAPI.prototype.joinwaitlist();

**Comment by ImGrumpy** [comment]
```
C:\bot\node_modules\plugbotapi\index.js:514
                        $( "#dj-button" ).trigger( "click" );
                        ^
ReferenceError: $ is not defined
    at PlugBotAPI.addBotDJ (C:\bot\node_modules\plugbotapi\index.js:514:4)
    at null._onTimeout (C:\bot\bot.js:1493:36)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

Tried, failed.  Maybe I'm not sure what you're suggesting?  I tried to add your code into the API (except the last line which actually calls it), then I tried to call it from my bot at the appropriate point.  I get what it's trying to do, but I'm not sure what's missing.
